left_wsg_50_gl:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - left_gripper_base_joint_gripper_left
    pid:
      p: 100.0
      d: 10.0

left_wsg_50_gr:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - left_gripper_base_joint_gripper_right
    pid:
      p: 100.0
      d: 10.0

right_wsg_50_gl:
  ros__parameters:
    type: position_controllers/JointGroupPositionController

    joints: 
      - right_gripper_base_joint_gripper_left
    pid:
      p: 100.0
      d: 10.0

right_wsg_50_gr:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - right_gripper_base_joint_gripper_right
    pid:
      p: 100.0
      d: 10.0      
    

wsg50_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - left_gripper_base_joint_gripper_right
      - left_gripper_base_joint_gripper_left
      - right_gripper_base_joint_gripper_right
      - right_gripper_base_joint_gripper_left
    pid:
      p: 100.0
      d: 10.0

